apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: label-studio-db
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 6Gi
  - target:
      group: build.openshift.io
      kind: BuildConfig
    patch: |-
      - op: replace
        path: /spec/source/git/uri
        value: https://github.com/redhat-na-ssa/flyingthings.git
      - op: replace
        path: /spec/source/contextDir
        value: components/label-studio/container/s2i
      - op: replace
        path: /spec/source/git/ref
        value: main
  - target:
      group: apps
      kind: Deployment
      name: label-studio
    path: patch-deployment.yaml
# - target:
  #     group: apps
  #     kind: Deployment
  #     name: label-studio-db
  #   patch: |-
  #     - op: replace
  #       path: /spec/replicas
  #       value: 0
  - path: patch-delete-db.yaml
  