apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: yolo-api
  # app.kubernetes.io/component: yolo-api
  # app.kubernetes.io/instance: yolo-api
  app.kubernetes.io/name: yolo-api
  app.kubernetes.io/part-of: yolo-api

resources:
- 1a-python-s2i-patch-bc.yaml
- 1b-base-via-source-bc.yaml
- 2a-base-via-docker-bc.yaml
- 2b-add-ffmpeg-bc.yaml
# - udi-custom.yaml
# - 3a-embed-model-s2i-bc.yaml
- is.yaml
