apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: label-studio
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: label-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      name: label-studio
  template:
    metadata:
      labels:
        name: label-studio
    spec:
      containers:
        - name: container
          image: >-
            image-registry.openshift-image-registry.svc:5000/modemo/labelstudio:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/app-root/src/.local
              name: label-studio-data
          resources: {}
      volumes:
        - name: label-studio-data
          persistentVolumeClaim:
            claimName: label-studio
  strategy:
    type: RollingUpdate
---
kind: Service
apiVersion: v1
metadata:
  name: label-studio
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: label-studio
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: label-studio
spec:
  to:
    kind: Service
    name: label-studio
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
