apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: autoscaling.openshift.io
      kind: ClusterAutoscaler
      name: default
    patch: |-
      - op: replace
        path: /spec/resourceLimits/maxNodesTotal
        value: 8
      - op: replace
        path: /spec/resourceLimits/cores
        value:
          min: 0
          max: 96
      - op: replace
        path: /spec/resourceLimits/memory
        value:
          min: 0
          max: 372
      - op: replace
        path: /spec/resourceLimits/gpus/0/max
        value: 8
