apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: sandbox
spec:
  limits:
    - type: Container
      default:
        memory: 1Gi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 100m
      max:
        cpu: '8'
        memory: 16Gi
