apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-bucket
spec:
  params:
    - name: SIMPLEVIS_DATA
      type: string
    - name: MINIO_ENDPOINT
      type: string
    - name: MINIO_BUCKET
      type: string
    - name: MINIO_ACCESSKEY
      type: string
    - name: MINIO_SECRETKEY
      type: string
  steps:
    - name: create-bucket
      image: ubi9:latest
      script: |
        cd $(workspaces.workspace.path) \
        && $(workspaces.source.path)/source/training/minio-setup-client.sh \
        && $(workspaces.source.path)/source/training/minio-create-bucket.sh \
        && pwd && ls -al
      env:
        - name: MINIO_ENDPOINT
          value: $(params.MINIO_ENDPOINT)
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: BASEDIR
          value: $(workspaces.source.path)/source/minio-client
        - name: MINIO_BUCKET
          value: $(params.MINIO_BUCKET)
        - name: MINIO_ACCESSKEY
          value: $(params.MINIO_ACCESSKEY)
        - name: MINIO_SECRETKEY
          value: $(params.MINIO_SECRETKEY)
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source
