apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: distribute-data
spec:
  steps:
    - name: distribute-data
      image: image-registry.openshift-image-registry.svc:5000/openshift/python:3.9-ubi8
      script: |
        cd $(workspaces.workspace.path)

        SOURCE_DIR=$(workspaces.source.path)
        BASEDIR=${SOURCE_DIR}/source/training

        $(workspaces.source.path)/source/training/02-distribute-files.py
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source
