apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: export-model
spec:
  params:
    - name: WEIGHTS
      type: string
    - name: BASE_MODEL
      type: string
    - name: SIMPLEVIS_DATA
      type: string
    - name: NAMESPACE
      type: string
  steps:
    - name: export-model
      image: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/yolo:latest
      script: |
        set -x \
        && $(workspaces.source.path)/source/training/export-model.sh \
        && ls -l $(params.SIMPLEVIS_DATA)/workspace
      env:
        - name: WEIGHTS
          value: $(params.WEIGHTS)
        - name: BASE_MODEL
          value: $(params.BASE_MODEL)
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: BASEDIR
          value: $(workspaces.source.path)/source/training-job
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source