apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: export-model
spec:
  params:
    - name: WEIGHTS
      type: string
    - name: BASE_MODEL
      type: string
    - name: SIMPLEVIS_DATA
      type: string
    - name: ocp-tablespace
      type: string
  steps:
    - name: export-model
      image: image-registry.openshift-image-registry.svc:5000/$(params.ocp-tablespace)/yolo:latest
      script: |
        set -x \
        && $(workspaces.source.path)/source/training/export-model.sh \
        && ls -l $(params.SIMPLEVIS_DATA)/workspace
      env:
        - name: WEIGHTS
          value: $(params.WEIGHTS)
        - name: BASE_MODEL
          value: $(params.BASE_MODEL)
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: BASEDIR
          value: $(workspaces.source.path)/source/training-job
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
  volumes:
    - name: dshm
      emptyDir:
          medium: Memory
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source