apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: train-model-cpu
spec:
  params:
    - name: SCRIPT
      type: string
    - name: IMAGE
      type: string
  steps:
    - name: train-model-using-cpu
      image: $(params.IMAGE)
      script: |
        $(params.SCRIPT)

        cd $(workspaces.scratch.path)

        source $(workspaces.source.path)/source/training/functions.sh && \
        model_training
      resources: {}
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /usr/local/lib/python3.9/site-packages/yolov5/training
          name: training
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 4Gi
    - name: training
      emptyDir: {}
  workspaces:
    - name: scratch
      mountPath: /source/scratch
      optional: true
    - name: source
      mountPath: /source