apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: training-summary
spec:
  params:
    - name: GIT_URL
      type: string
    - name: GIT_REVISION
      type: string
    - name: NAMESPACE
      type: string
    - name: BATCH_SIZE
      type: string
    - name: NUM_EPOCHS
      type: string
    - name: IMG_RESIZE
      type: string
    - name: MAX_WIDTH
      type: string
    - name: WEIGHTS
      type: string
    - name: BASE_MODEL
      type: string
    - name: MINIO_ENDPOINT
      type: string
    - name: DATASET_ZIP
      type: string
    - name: SIMPLEVIS_DATA
      type: string
    - name: MINIO_BUCKET
      type: string
    - name: MINIO_ACCESSKEY
      type: string
    - name: MINIO_SECRETKEY
      type: string
    - name: DEPLOY
      type: string
    - name: MODEL_NAME
      type: string
  steps:
    - name: summary
      image: alpine
      script: |
        echo "Training run parameters:" \
        && echo "$HOSTNAME" \
        && echo "GIT_URL: $GIT_URL" \
        && echo "GIT_REVISION: $GIT_REVISION" \
        && echo "NAMESPACE: $NAMESPACE" \
        && echo "BATCH_SIZE: $BATCH_SIZE" \
        && echo "NUM_EPOCHS: $NUM_EPOCHS" \
        && echo "IMG_RESIZE: $IMG_RESIZE" \
        && echo "MAX_WIDTH: $MAX_WIDTH" \
        && echo "WEIGHTS: $WEIGHTS" \
        && echo "BASE_MODEL: $BASE_MODEL" \
        && echo "MINIO_ENDPOINT: $MINIO_ENDPOINT" \
        && echo "DATASET_ZIP: $DATASET_ZIP" \
        && echo "SIMPLEVIS_DATA: $SIMPLEVIS_DATA" \
        && echo "MINIO_BUCKET: $MINIO_BUCKET" \
        && echo "MINIO_ACCESSKEY: $MINIO_ACCESSKEY" \
        && echo "MINIO_SECRETKEY: $MINIO_SECRETKEY" \
        && echo "DEPLOY: $DEPLOY" \
        && echo "MODEL_NAME: $MODEL_NAME"
      env:
      - name: GIT_URL
        value: $(params.GIT_URL)
      - name: GIT_REVISION
        value: $(params.GIT_REVISION)
      - name: NAMESPACE
        value: $(params.NAMESPACE)
      - name: BATCH_SIZE
        value: $(params.BATCH_SIZE)
      - name: NUM_EPOCHS
        value: $(params.NUM_EPOCHS)
      - name: IMG_RESIZE
        value: $(params.IMG_RESIZE)
      - name: MAX_WIDTH
        value: $(params.MAX_WIDTH)
      - name: WEIGHTS
        value: $(params.WEIGHTS)
      - name: BASE_MODEL
        value: $(params.BASE_MODEL)
      - name: MINIO_ENDPOINT
        value: $(params.MINIO_ENDPOINT)
      - name: DATASET_ZIP
        value: $(params.DATASET_ZIP)
      - name: SIMPLEVIS_DATA
        value: $(params.SIMPLEVIS_DATA)
      - name: MINIO_BUCKET
        value: $(params.MINIO_BUCKET)
      - name: MINIO_ACCESSKEY
        value: $(params.MINIO_ACCESSKEY)
      - name: MINIO_SECRETKEY
        value: $(params.MINIO_SECRETKEY)
      - name: DEPLOY
        value: $(params.DEPLOY)
      - name: MODEL_NAME
        value: $(params.MODEL_NAME)
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source
