apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: train-model-gpu
spec:
  params:
    - name: BATCH_SIZE
      type: string
    - name: NUM_EPOCHS
      type: string
    - name: WEIGHTS
      type: string
    - name: BASE_MODEL
      type: string
    - name: SIMPLEVIS_DATA
      type: string
    - name: NAMESPACE
      type: string
  steps:
    - name: train-model-using-gpu
      image: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/yolo:latest
      script: |
        set -x \
        && $(workspaces.source.path)/source/training/03-run-training.sh \
        && ls -l $(params.SIMPLEVIS_DATA)/workspace
      env:
        - name: BATCH_SIZE
          value: $(params.BATCH_SIZE)
        - name: NUM_EPOCHS
          value: $(params.NUM_EPOCHS)
        - name: WEIGHTS
          value: $(params.WEIGHTS)
        - name: BASE_MODEL
          value: $(params.BASE_MODEL)
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: BASEDIR
          value: $(workspaces.source.path)/source/training-job
      resources:
        limits:
          nvidia.com/gpu: 1
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /usr/local/lib/python3.9/site-packages/yolov5/training
          name: training
  volumes:
    - name: dshm
      emptyDir:
          medium: Memory
    - name: training
      emptyDir: {}
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source