apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: distribute-data
  namespace: flyingthings-standalone
spec:
  params:
    - name: SIMPLEVIS_DATA
      type: string
  steps:
    - name: distribute-data
      image: registry.access.redhat.com/ubi9/python-39
      script: |
        cd $(params.SIMPLEVIS_DATA)/workspace \
        && $(workspaces.source.path)/source/training/02-distribute-files.py
      env:
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: BASEDIR
          value: $(workspaces.source.path)/source/training
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source
