apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-classfile
spec:
  params:
    - name: SIMPLEVIS_DATA
      type: string
    - name: ocp-tablespace
      type: string
  steps:
    - name: distribute-data
      image: image-registry.openshift-image-registry.svc:5000/$(params.ocp-tablespace)/base-ubi9:latest
      script: |
        cp $(workspaces.source.path)/source/training/classes.yaml.j2 $(params.SIMPLEVIS_DATA)/workspace/datasets \
        && cd $(params.SIMPLEVIS_DATA)/workspace/datasets \
        && $(workspaces.source.path)/source/training/01-create-classfile.py \
        && cat classes.yaml \
        && mv classes.yaml $(params.SIMPLEVIS_DATA)/workspace
      env:
        - name: SIMPLEVIS_DATA
          value: $(params.SIMPLEVIS_DATA)
        - name: BASEDIR
          value: $(workspaces.source.path)/source/training
  workspaces:
    - name: workspace
      mountPath: /opt/app-root/src/simplevis-data/workspace
    - name: source
      mountPath: /source
