apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: train-model-run-
  annotations:
    chains.tekton.dev/signed: 'true'
  labels:
    tekton.dev/pipeline: train-model
spec:
  podTemplate:
    tolerations:
      - key: nvidia-gpu-only
        operator: Exists
        effect: NoSchedule
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
  params:
    - name: BATCH_SIZE
      value: '-1'
    - name: DATASET_ZIP
      value: flyingthings-yolo.zip
    - name: GIT_REVISION
      value: main
    - name: GIT_URL
      value: 'https://github.com/redhat-na-ssa/flyingthings.git'
    - name: GPU_TIMEOUT
      value: 12m
    - name: IMG_RESIZE
      value: 'Y'
    - name: MAX_WIDTH
      value: '200'
    - name: MODEL_BASE
      value: yolov5s.pt
    - name: MODEL_NAME
      value: model-flyingthings
    - name: NAMESPACE
      value: ml-demo
    - name: NUM_EPOCHS
      value: '100'
  pipelineRef:
    name: train-model
  serviceAccountName: pipeline
  timeouts:
    pipeline: 3h0m0s
  workspaces:
    - name: source
      volumeClaimTemplate:
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: tekton
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
