apiVersion: 1

# list of datasources to insert/update depending
# on what's available in the database
datasources:
 - name: 'Prometheus'
   type: 'prometheus'
   access: 'proxy'
   org_id: 1
   url: 'http://prometheus:9090'
   is_default: false
   version: 1
   editable: true
